/**
 * CSV generation utilities for drone export
 */

import { ExportData, ExportOptions } from '@/domain/types';

/**
 * Converts export data to CSV string
 */
export function generateCSV(
  exportData: ExportData,
  options: ExportOptions = { includeHeader: true, includeMetadata: true }
): string {
  const lines: string[] = [];
  
  // Add metadata as comments if enabled
  if (options.includeMetadata) {
    lines.push(`# Vertimage Drone Export - ${exportData.metadata.exportDate}`);
    lines.push(`# Generated by Vertimage v${exportData.metadata.version}`);
    lines.push('');
    lines.push('# Export Metadata:');
    lines.push(`# Total Drones: ${exportData.metadata.totalDrones}`);
    lines.push(`# Active Drones: ${exportData.metadata.activeDrones}`);
    lines.push(`# Filtered Drones: ${exportData.metadata.filteredDrones}`);
    lines.push(`# Image Size: ${exportData.metadata.imageWidth}x${exportData.metadata.imageHeight}px`);
    lines.push(`# Brightness Threshold: ${(exportData.metadata.brightnessThreshold * 100).toFixed(1)}%`);
    lines.push(`# Sampling Radius: ${exportData.metadata.samplingRadius}px`);
    lines.push('');
  }
  
  // Add CSV header
  if (options.includeHeader) {
    lines.push('Drone ID,X,Y,Red,Green,Blue,Brightness %');
  }
  
  // Add data rows
  exportData.drones.forEach(drone => {
    lines.push(
      `${drone.droneId},${drone.x},${drone.y},${drone.red},${drone.green},${drone.blue},${drone.brightness}`
    );
  });
  
  return lines.join('\n');
}

/**
 * Downloads CSV data as a file
 */
export function downloadCSV(
  csvContent: string,
  filename: string = 'vertimage-drones.csv'
): void {
  const blob = new Blob([csvContent], { 
    type: 'text/csv;charset=utf-8;' 
  });
  
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Clean up
  URL.revokeObjectURL(url);
}

/**
 * Generates a timestamp-based filename
 */
export function generateFilename(prefix: string = 'vertimage-drones'): string {
  const timestamp = new Date()
    .toISOString()
    .replace(/[:.]/g, '-')
    .slice(0, -5); // Remove milliseconds and 'Z'
  
  return `${prefix}-${timestamp}.csv`;
}

/**
 * Validates export data before generating CSV
 */
export function validateExportData(exportData: ExportData): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];
  
  if (!exportData.drones || exportData.drones.length === 0) {
    errors.push('No drone data available for export');
  }
  
  if (!exportData.metadata) {
    errors.push('Missing export metadata');
  }
  
  // Validate drone data structure
  exportData.drones.forEach((drone, index) => {
    if (typeof drone.droneId !== 'number') {
      errors.push(`Invalid drone ID at row ${index + 1}`);
    }
    
    if (typeof drone.x !== 'number' || typeof drone.y !== 'number') {
      errors.push(`Invalid coordinates at row ${index + 1}`);
    }
    
    if (
      typeof drone.red !== 'number' ||
      typeof drone.green !== 'number' ||
      typeof drone.blue !== 'number' ||
      drone.red < 0 || drone.red > 255 ||
      drone.green < 0 || drone.green > 255 ||
      drone.blue < 0 || drone.blue > 255
    ) {
      errors.push(`Invalid RGB values at row ${index + 1}`);
    }
    
    if (
      typeof drone.brightness !== 'number' ||
      drone.brightness < 0 ||
      drone.brightness > 100
    ) {
      errors.push(`Invalid brightness value at row ${index + 1}`);
    }
  });
  
  return {
    valid: errors.length === 0,
    errors,
  };
}